POST http://localhost:5000/directors/
Content-Type: application/json

{
  "name": "New_director44"
}

###

GET http://localhost:5000/directors/
Accept: application/json

###

GET http://localhost:5000/directors/23
Accept: application/json

###

PUT http://localhost:5000/directors/21
Accept: application/json
Content-Type: application/json

{
  "name": "superka_test"
}

###

DELETE http://localhost:5000/directors/24
Accept: application/json

###

PATCH http://localhost:5000/directors/21
Accept: application/json
Content-Type: application/json

{
  "name": "Director_Test"
}

###