POST http://localhost:5000/genres/
Content-Type: application/json

{
  "name": "FANTASTIC"
}

###

GET http://localhost:5000/genres/
Accept: application/json

###

GET http://localhost:5000/genres/2
Accept: application/json

###

PUT http://localhost:5000/genres/20
Accept: application/json
Content-Type: application/json

{
  "name": "New_Genre"
}

###

DELETE http://localhost:5000/genres/20
Accept: application/json

###

PATCH http://localhost:5000/genres/1
Accept: application/json
Content-Type: application/json

{
  "name": "superka"
}

###